### ISSUE TITLE
PRACTICA #4 CALCULADORA BASICA 

### ISSUE THREAD

**Issue by magaly1311** [SistemasTecTlaxiaco/practica-de-calculadora-en-consola-y-windows-form-equipo-m-a-r-topicos-a-p#1]
**ARCHIVOS de Windows Form**

[Calculadora (1).zip](https://github.com/SistemasTecTlaxiaco/practica-de-calculadora-en-consola-y-windows-form-equipo-m-a-r-topicos-a-p/files/8301480/Calculadora.1.zip)
[Operacion (2).zip](https://github.com/SistemasTecTlaxiaco/practica-de-calculadora-en-consola-y-windows-form-equipo-m-a-r-topicos-a-p/files/8301481/Operacion.2.zip)

**Comment by magaly1311** [comment]
**ARCHIVOS DE CONSOLA Y PDF**

[Operaciones_Basicas.zip](https://github.com/SistemasTecTlaxiaco/practica-de-calculadora-en-consola-y-windows-form-equipo-m-a-r-topicos-a-p/files/8321375/Operaciones_Basicas.zip)
[PRACTICA 4 TOPICOS AVANZADOS DE PROGRAMACION.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-calculadora-en-consola-y-windows-form-equipo-m-a-r-topicos-a-p/files/8321377/PRACTICA.4.TOPICOS.AVANZADOS.DE.PROGRAMACION.pdf)

**Comment by JudithReynaCS** [comment]
Calificación:18.4%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
